### ISSUE TITLE
Xfwm theme and xfce-panel issue

### ISSUE THREAD

**Issue by sussypotato** [WMCB-Tech/iceberg-gtk-theme#1]
This image describes it all
![susss](https://user-images.githubusercontent.com/86041547/127256642-e9e43c78-57c5-47b7-a4f5-753fbba0b91d.png)

<b>Xfce panel</b>
The systray and other icons, excluding application list, has some sort of non-transparent background, where it should be transparent. I do use custom gtk.css for the panel, but I've tried without the custom css also. This issue still appears

<b>Xfwm theme</b>
The icon hover effects are a bit odd. I mean, if you hover any icon [close/minimize/maximize etc], their color become darker. Dark foreground on dark background is not a good choice.

Some other issues are also found, but they're not pretty major. Hope to see this project become great :D
Sorry for my broken English

**Comment by WMCB-Tech** [comment]
You are very welcome to report this. although what i used is oomox, probably i darken it too much and didn't see it properly, apparently oomox didn't add preview for minimize maximize windows

i might adjust it see how it goes. the oomox preset file is in my dotfiles repo so you may look at it

**Comment by WMCB-Tech** [comment]
actually i did fix the issue when the minimize maximize becomes dark, it should be lighter now but would be lighter, although i might pick appropriate color for this

![image](https://user-images.githubusercontent.com/65075766/127275040-15e6adfb-e2b5-4e58-9bdd-520d05945a1b.png)

**Comment by WMCB-Tech** [comment]
Ok so i tested xfce as well and it kinda looks better now after adjusting things
check the doodles

![image](https://user-images.githubusercontent.com/65075766/127277858-fc5a4433-a966-497a-bf3e-c3714a3e49e6.png)

**Comment by sussypotato** [comment]
This looks better :D I was thinking, if the Xfwm titlebar's height would be increased, you know, to make the CSD titlebar and Xfce titlebar look similar. CSDs are a mess

**Comment by WMCB-Tech** [comment]
i recently updated it. you may test it now
